[features]
seeds = false
skip-lint = false

[programs.testnet]
binary_options = "JCqZPL84bJQKfQ1FZ4cYSWddYNpQCBXPjowjkCcdn9ZB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.testnet.solana.com"
[test]
startup_wait = 20000
